version: '3.8'

services:
  pyscheduler:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PYSCHED_DATA_PATH=/data
      - PYSCHED_SECRET_KEY=${PYSCHED_SECRET_KEY:-your-secret-key-change-me-in-production}
      - PYSCHED_DEBUG=${PYSCHED_DEBUG:-false}
      
      # Security Settings
      - PYSCHED_DEFAULT_API_KEY=${PYSCHED_DEFAULT_API_KEY:-your-default-api-key-change-me}
      - PYSCHED_RATE_LIMIT_ENABLED=${PYSCHED_RATE_LIMIT_ENABLED:-true}
      - PYSCHED_DEFAULT_SCRIPT_TIMEOUT=${PYSCHED_DEFAULT_SCRIPT_TIMEOUT:-300}
      - PYSCHED_DEFAULT_MEMORY_LIMIT=${PYSCHED_DEFAULT_MEMORY_LIMIT:-512}
      
      # Email Settings (Optional)
      - SMTP_SERVER=${SMTP_SERVER:-mail.smtp2go.com}
      - SMTP_PORT=${SMTP_PORT:-2525}
      - SMTP_USERNAME=${SMTP_USERNAME:-}
      - SMTP_PASSWORD=${SMTP_PASSWORD:-}
      - FROM_EMAIL=${FROM_EMAIL:-pyscheduler@example.com}
      
      # Redis Settings
      - REDIS_URL=redis://localhost:6379/0
      
    volumes:
      - pyscheduler_data:/data
      - pyscheduler_logs:/var/log
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  pyscheduler_data:
    driver: local
  pyscheduler_logs:
    driver: local