# PyScheduler - Simple Docker Compose Example
# Copy this file to docker-compose.yml and customize as needed

services:
  pyscheduler:
    image: moteez/pyscheduler:latest
    container_name: pyscheduler
    ports:
      - "8000:8000"
    environment:
      # Core Settings
      - PYSCHED_DATA_PATH=/data
      - PYSCHED_SECRET_KEY=your-secret-key-change-me-in-production
      
      # Admin User Settings (set PYSCHED_ADMIN_PASSWORD or secure random will be generated)
      - PYSCHED_ADMIN_USERNAME=admin
      - PYSCHED_ADMIN_PASSWORD=
      - PYSCHED_ADMIN_EMAIL=admin@localhost
      
      # Email Settings (Optional - used as fallback if database settings not configured)
      - SMTP_SERVER=
      - SMTP_PORT=2525
      - SMTP_USERNAME=
      - SMTP_PASSWORD=
      - FROM_EMAIL=
      
    volumes:
      - pyscheduler_data:/data
      - pyscheduler_logs:/var/log
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  pyscheduler_data:
    driver: local
  pyscheduler_logs:
    driver: local