services:
  tempo:
    image: moteez/tempo:latest
    build: .  # Uncomment for local development
    ports:
      - "8000:8000"
    environment:
      # Core Settings
      - TEMPO_DATA_PATH=/data
      - TEMPO_SECRET_KEY=${TEMPO_SECRET_KEY:-your-secret-key-change-me-in-production}
      
      # Admin User Settings (set TEMPO_ADMIN_PASSWORD or secure random will be generated)
      - TEMPO_ADMIN_USERNAME=${TEMPO_ADMIN_USERNAME:-admin}
      - TEMPO_ADMIN_PASSWORD=${TEMPO_ADMIN_PASSWORD:-}
      - TEMPO_ADMIN_EMAIL=${TEMPO_ADMIN_EMAIL:-admin@localhost}
      
      # Email Settings (Optional - used as fallback if database settings not configured)
      - SMTP_SERVER=${SMTP_SERVER:-}
      - SMTP_PORT=${SMTP_PORT:-2525}
      - SMTP_USERNAME=${SMTP_USERNAME:-}
      - SMTP_PASSWORD=${SMTP_PASSWORD:-}
      - FROM_EMAIL=${FROM_EMAIL:-}
      
    volumes:
      - tempo_data:/data
      - tempo_logs:/var/log
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  tempo_data:
    driver: local
  tempo_logs:
    driver: local